config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/login', to: 'logins#loginform', as: 'login_login'
  post '/login', to: 'logins#handle_login'
  post '/logout', to: 'logins#logout'

  get '/profiles', to: 'profiles#index', as: "profiles"
  get '/profiles/new', to: 'profiles#new', as: "new_profile"
  post '/profiles', to: 'profiles#create'
  get "/profiles/:id", to: "profiles#show", as: 'profile'
  get '/profiles/:id/edit', to: "profiles#edit", as: "edit_profile"
  patch '/profiles/:id', to: "profiles#update"
  delete "/profiles/:id", to: "profiles#destroy"

  get '/blogs', to: 'blogs#index', as: "blogs"
  get '/blogs/new', to: 'blogs#new', as: "new_blog"
  post '/blogs', to: 'blogs#create'
  get "/blogs/:id", to: "blogs#show", as: 'blog'
  get '/blogs/:id/edit', to: "blogs#edit", as: "edit_blog"
  patch '/blogs/:id', to: "blogs#update"
  delete "/blogs/:id", to: "blogs#destroy"

  get '/posts', to: 'posts#index', as: "posts"
  get '/posts/new', to: 'posts#new', as: "new_post"
  post '/posts', to: 'posts#create'
  get "/posts/:id", to: "posts#show", as: 'post'
  get '/posts/:id/edit', to: "posts#edit", as: "edit_post"
  patch '/posts/:id', to: "posts#update"
  delete "/posts/:id", to: "posts#destroy"

  get '/summaries', to: 'summaries#index', as: "summaries"
  get '/summaries/new', to: 'summaries#new', as: "new_summary"
  post '/summaries', to: 'summaries#create'
  get "/summaries/:id", to: "summaries#show", as: 'summary'
  get '/summaries/:id/edit', to: "summaries#edit", as: "edit_summary"
  patch '/summaries/:id', to: "summaries#update"
  delete "/summaries/:id", to: "summaries#destroy"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :summaries
    has_many :profiles, through: :summaries

    validates :title, :text, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :profile

    validates :post, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
    has_many :posts
    has_many :summaries
    has_many :blogs, through: :summaries

    has_secure_password

    validates_presence_of :fullname, message: "Can't be blank"
end

app/models/summary.rb
class Summary < ApplicationRecord
    belongs_to :profile
    belongs_to :blog

    validates_presence_of :summary, message: "Can't be blank"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :logged_in_user, :logged_in?

    def logged_in_user
        if session[:profile_id]
            @logged_in_user = Profile.find_by(id: session[:profile_id])
        end
    end

    def logged_in?
        !!logged_in_user
    end

    def check_if_logged_in
        redirect_to login_login_path unless logged_in?
    end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    def index
        @blogs = Blog.all
    end

    def new
        @blog = Blog.new
    end

    def create
        @blog = Blog.new(params.require(:blog).permit(:title, :text))
        if @blog.valid?
            @blog.save
            redirect_to new_summary_path(blog: @blog)
        else
            flash[:error] = @blog.errors.full_messages
            redirect_to new_blog_path
        end
    end

    def show
        @blog = Blog.find(params[:id])
    end

    def edit
        @blog = Blog.find(params[:id])
    end

    def update
        @blog = Blog.find(params[:id])
        @blog.update(params.require(:blog).permit(:title, :text))
        if @blog.valid?
            @blog.save
            redirect_to blog_path(@blog)
        else
            flash[:error] = @blog.errors.full_messages
            redirect_to edit_blog_path(@blog)
        end
    end

    def destroy
        @blog = Blog.find(params[:id])
        @blog.destroy
        redirect_to blogs_path
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
      def loginform
        @errors = flash[:errors]
      end
    
      def handle_login
        @profile = Profile.find_by(fullname: params[:fullname])
        if @profile && @profile.authenticate(params[:password])
          session[:profile_id] = @profile.id
          redirect_to @profile
        else
          flash[:error] = "Invalid username or password"
          redirect_to login_login_path
        end
      end

      def logout
        session[:profile_id] = nil
        redirect_to profiles_path
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.create(params.require(:post).permit(:post, :profile_id))
        if @post.valid?
            redirect_to profile_path(@post.profile_id)
        else
            flash[:message] = @post.errors.full_messages
            redirect_to profile_path(@post.profile_id)
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        @post.update(params.require(:post).permit(:post))
        if @post.valid?
            redirect_to profile_path(@post.profile)
        else
            flash[:error] = @post.errors.full_messages
            redirect_to edit_post_path(@post)
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to profile_path(@post.profile)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    before_action :check_if_logged_in, only: [:edit]

    def index
        @profiles = Profile.all
    end

    def new
        @profile = Profile.new
    end

    def create
        @profile = Profile.create(params.require(:profile).permit(:fullname, :password))
        if @profile.valid?
            # session[:profile_id] = nil
            session[:profile_id] = @profile.id
            redirect_to @profile
        else
            flash[:error] = @profile.errors.first[1]
            redirect_to new_profile_path
        end
    end

    def show
        @profile = Profile.find(params[:id])
        @newpost = Post.new
    end

    def edit
        @profile = Profile.find(params[:id])
        unless logged_in? && logged_in_user.id == @profile.id
            redirect_to @profile
        end
    end

    def update
        @profile = Profile.find(params[:id])
        @profile.update(params.require(:profile).permit(:fullname, :password))
        if @profile.valid?
            redirect_to profile_path(@profile)
        else
            flash[:error] = @profile.errors.first[1]
            redirect_to edit_profile_path(@profile)
        end
    end

    def destroy
        @profile = Profile.find(params[:id])
        @profile.blogs.destroy
        @profile.summaries.destroy
        @profile.posts.destroy
        @profile.destroy
        redirect_to profiles_path
    end
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
    
    before_action :check_if_logged_in
    
    def index
        @summaries = Summary.all
    end

    def new
        @summary = Summary.new
        @blog = Blog.find(params[:blog])
    end

    def create
        @summary = Summary.new(params.require(:summary).permit(:summary, :profile_id, :blog_id))
        @summary.profile_id = session[:profile_id]
        if @summary.valid?
            @summary.save
            redirect_to profile_path(@summary.profile)
        else
            flash[:error] = @summary.errors.first[1]
            redirect_to new_summary_path(blog: Blog.last.id)
        end
    end

    def show
        @summary = Summary.find(params[:id])
    end

    def edit
        @summary = Summary.find(params[:id])
    end

    def update
        @summary = Summary.find(params[:id])
        @summary.update(params.require(:summary).permit(:summary, :profile_id, :blog_id))
        if @summary.valid?
            redirect_to profile_path(@summary.profile)
        else
            flash[:error] = @summary.errors.first[1]
            redirect_to edit_summary_path(@summary)
        end
    end

    def destroy
        @summary = Summary.find(params[:id])
        @summary.blog.destroy
        @summary.destroy
        redirect_to profile_path(@summary.profile)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/views/blogs/edit.html.erb
<h1>What would you like to edit?</h1>
<hr>
<br>

<% if flash[:error] %>
    <% flash[:error].each do |error| %>
        <p style="color: red">
            <%= error %>
        </p>
    <% end %>
<% end %>

<%= form_for @blog do |f| %>
    Title:
    <%= f.text_area :title, :cols => "50", :rows => "1" %>
    <br><br>
    <%= f.text_area :text, :cols => "85", :rows => "40" %>
    <br><br><br>
    <%= f.submit %>
<% end %>

app/views/blogs/new.html.erb
<h1>What is your blog about?</h1>
<hr>
<br>

<% if flash[:error] %>
    <% flash[:error].each do |error| %>
        <p style="color: red">
            <%= error %>
        </p>
    <% end %>
<% end %>

<%= form_for @blog do |f| %>
    Title:
    <%= f.text_area :title, :cols => "50", :rows => "1" %>
    <br><br>
    <%= f.text_area :text, :cols => "85", :rows => "40" %>
    <br><br><br>
    <%= f.submit %>
<% end %>

app/views/blogs/show.html.erb
<h1> <%= @blog.title %> </h1>
<hr>
<br>

<p> <%= @blog.text %> </p>

<br>
<% @blog.summaries.each do |summary| %>
    <% if logged_in? && logged_in_user.id == summary.profile_id %>
        <%= link_to "Edit this blog", edit_blog_path %>
    <% end %>
<% end %>
<br><br>

<% @blog.profiles.each do |profiles| %>
<%= link_to "Back to profile", profile_path(profiles) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Visual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/loginform.html.erb
<h1>Sign In</h1>
<hr>
<br>

<% if flash[:error] %>
    <p style='color: red'>
        <%= flash[:error] %>
    </p>
<% end %>

<%= form_tag "/login", method: "POST" do %>
  Name: <%= text_field_tag :fullname %>
  Password: <%= password_field_tag :password %>
  <%= submit_tag "Log In" %>
<% end %>

app/views/posts/edit.html.erb
<h1> What would you like to change? </h1>
<hr>
<br>

<% if flash[:error] %>
    <% flash[:error].each do |error| %>
        <p style="color: red">
            <%= error %>
        </p>
    <% end %>
<% end %>

<%= form_for @post do |f| %>
    <%= f.text_area :post, :cols => "85", :rows => "2" %>
    <br><br>
    <%= f.submit "Update" %>
<% end %>
<br><br>
<%= button_to "Delete", post_path(@post), method: :delete %>

app/views/posts/show.html.erb
# <h1>What would you like to do with this post?</h1>
# <hr>
# <br>
# <p> <%= @post.post %> </p>

# <%= link_to "Edit", edit_post_path(@post) %>
# <p>or</p>

# <%= link_to "Delete", post_path(@post), method: :delete %>

app/views/profiles/edit.html.erb
<h1> What would you like your new name to be? </h1>
<hr>
<br>

<% if flash[:error] %>
    <p style='color: red'>
        <%= flash[:error] %>
    </p>
<% end %>

<%= form_for @profile do |f| %>
    Name: <%= f.text_area :fullname, :cols => "25", :rows => "1" %>
    <%= f.submit %>
<% end %>

app/views/profiles/index.html.erb
<h1>Profiles</h1>
<hr>

<ul class="bulletremoval">
    <% @profiles.each do |profiles| %>
        <li>
            <%= link_to profiles.fullname, profile_path(profiles)%>
        </li>
    <% end %>
</ul>

<% if !logged_in? %>
<hr><br>
    <p> <%= link_to "Sign In", login_login_path %> <br>~<br> <%= link_to "Sign Up", new_profile_path %> </p>
<% end %>

app/views/profiles/new.html.erb
<h1>Sign Up</h1>
<hr>
<br>

<% if flash[:error] %>
    <p style='color: red'>
        <%= flash[:error] %>
    </p>
<% end %>

<%= form_for @profile do |f| %>
    Name: <%= f.text_area :fullname, :cols => "25", :rows => "1" %>
    Password: <%= f.password_field :password %>
    <%= f.submit %>
<% end %>

app/views/profiles/show.html.erb
<h1> <%=@profile.fullname%> </h1> 

<%= link_to "Search Profiles", profiles_path %>

<br><br>
<% if logged_in? && logged_in_user.id == @profile.id %>
    ~ <%= link_to "Edit Name", edit_profile_path %>
<% end %>
<hr>

<h2>Posts</h2> 

<% if flash[:message] %>
    <% flash[:message].each do |error| %>
        <p style="color: red">
            <%= error %>
        </p>
    <% end %>
<% end %>

<% if logged_in? && logged_in_user.id == @profile.id %>
    <%= form_for @newpost do |f| %>
        <%= f.hidden_field :profile_id, value: @profile.id %>
        What's on your mind? <%= f.text_area :post, :cols => "85", :rows => "1" %>
        <%= f.submit %>
    <% end %>
<% end %>

<ul class="bulletremoval">
    <% @profile.posts.each do |post| %>
        <li> 
            <p class="list"> <%= post.post %> 
                <% if logged_in? && logged_in_user.id == @profile.id %>
                    ~ <%= link_to "Edit", edit_post_path(post), class: "hidden"%>
                <% end %>
            </p>
        </li>
    <% end %>
</ul>

<hr>

<h2>Blogs</h2>
<% if logged_in? && logged_in_user.id == @profile.id %>
    <%= link_to "Create a Blog!", new_blog_path %>
<% end %>

<ul class="bulletremoval">
    <% @profile.summaries.each do |summary| %>
        <li>
            <%= link_to summary.blog.title, blog_path(summary.blog) %>
            <br>
            <p class="list"><%= summary.summary %> </p>
                <% if logged_in? && logged_in_user.id == @profile.id %>
                    ~<%= link_to "Edit", edit_summary_path(summary), class:"hidden"%>
                <% end %>
            <br><br>
        </li>
    <% end %>
</ul>

<hr><br>
<% if logged_in? && logged_in_user.id == @profile.id %>
    <%= button_to "Log Out", "/logout" %>
    <br>
    <%= button_to "Delete Profile", @profile, method: :delete %>
<% end %>

app/views/summaries/edit.html.erb
<h1> What would you like to change? </h1>
<hr>
<br>

<% if flash[:error] %>
    <p style='color: red'>
        <%= flash[:error] %>
    </p>
<% end %>

<%= form_for @summary do |f| %>
    <%= f.text_area :summary, :cols => "85", :rows => "10" %>
    <br><br>
    <%= f.submit "Update" %>
<% end %>
<br><br>
<%= button_to "Delete", summary_path(@summary), method: :delete %>

app/views/summaries/index.html.erb
<h1>Summaries</h1>

app/views/summaries/new.html.erb
<h1>Add a summary for your profile!</h1>
<hr>
<br>

<% if flash[:error] %>
    <p style='color: red'>
        <%= flash[:error] %>
    </p>
<% end %>

<%= form_for @summary do |f| %>
    Blog Title: 
    <%= @blog.title %>
    <%= f.hidden_field :blog_id, value: @blog.id %>
    <br><br>
    Summary:
    <%= f.text_area :summary, :cols => "85", :rows => "20" %>
    <br><br>
    
    <%= f.submit %>
<% end %>